
server:
    port: 8081
    error:
        include-message: always


spring:
    datasource: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        url: jdbc:mysql://localhost:3306/classrecorder
        password: Napeekkaiser12
    jpa:
        hibernate:
            ddl-auto: update
            format_sql: true
        show-sql: true
        open-in-view: true
    logging:
        level:
        org.springframework.transaction.interceptor: DEBUG
